'use client'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useState } from 'react'
import { ArrowLeft, Save } from 'lucide-react'
import { useAppData } from '@/components/data/app-data-provider'
import { PageHeader } from '@/components/page-header'
import { Button, buttonVariants } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select } from '@/components/ui/select'

export default function NovaAssinaturaPage(){const router=useRouter();const {barbershop,clients,plans,insertRecord}=useAppData();const [form,setForm]=useState({clientId:'',planId:'',startDate:'',dueDate:'',price:'',status:'ativo'});const [message,setMessage]=useState('');const set=(k:keyof typeof form,v:string)=>setForm(c=>({...c,[k]:v}));async function save(){const client=clients.find(c=>c.id===form.clientId);const plan=plans.find(p=>p.id===form.planId);if(!client||!plan||!form.startDate||!form.dueDate){setMessage('Preencha cliente, plano e datas.');return}const result=await insertRecord('subscriptions',{barbershop_id:barbershop.id,client_id:client.id,client_name:client.name,plan_id:plan.id,plan_name:plan.name,price:Number(form.price.replace(',','.'))||plan.price,start_date:form.startDate,due_date:form.dueDate,status:form.status,credits_used:0,credits_total:plan.credits??null});if(result.error){setMessage(result.error);return}router.push('/assinaturas')}
return <div><PageHeader title="Nova assinatura" description="Associe um cliente a um plano."><Link href="/assinaturas" className={buttonVariants({variant:'outline',size:'sm'})}><ArrowLeft className="size-4"/>Voltar</Link></PageHeader><Card className="mx-auto max-w-2xl p-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Cliente"><Select value={form.clientId} onChange={e=>set('clientId',e.target.value)}><option value="">Selecionar</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field><Field label="Plano"><Select value={form.planId} onChange={e=>{set('planId',e.target.value);const p=plans.find(x=>x.id===e.target.value);if(p)set('price',String(p.price).replace('.',','))}}><option value="">Selecionar</option>{plans.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select></Field><Field label="Início"><Input type="date" value={form.startDate} onChange={e=>set('startDate',e.target.value)}/></Field><Field label="Próximo vencimento"><Input type="date" value={form.dueDate} onChange={e=>set('dueDate',e.target.value)}/></Field><Field label="Valor"><Input value={form.price} onChange={e=>set('price',e.target.value)}/></Field><Field label="Status"><Select value={form.status} onChange={e=>set('status',e.target.value)}><option value="ativo">Ativo</option><option value="vencendo">Vencendo</option><option value="vencido">Vencido</option><option value="cancelado">Cancelado</option></Select></Field></div>{message?<p className="mt-4 text-sm">{message}</p>:null}<Button variant="gold" className="mt-5 w-full" onClick={save}><Save className="size-4"/>Salvar assinatura</Button></Card></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
